"""Initial migration.

Revision ID: 08abf08e572e
Revises: 
Create Date: 2025-09-02 13:40:54.780259

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '08abf08e572e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employees',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('salary', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('employees')
    # ### end Alembic commands ###

def upgrade():
    op.rename_table('department', 'departments')

def downgrade():
    op.rename_table('departments', 'department')
